[package]
name = "journal_explorer"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", default-features = false, features = ["image", "svg", "tiny-skia", "lazy"] }
rfd = "0.15.3"
iced_aw = "0.12.2"
anyhow = "1.0.98"
